<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Elastic Search Base for Magento 2
 */
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Amasty_ElasticSearch/js/system/config/catalog-group-show": {
                "isEngineValid": <?= $escaper->escapeJs((int)$block->getData('is_engine_valid')) ?>
                }
            }
        }
</script>
