<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Elastic Search Base for Magento 2
 */
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Amasty\ElasticSearch\ViewModel\Elasticsearch\SuggestNotificationViewModel $viewModel
 */
$viewModel = $block->getData('viewModel');
?>
<?php if ($viewModel->shouldShowNotification()): ?>
    <div>
        <p class="message message-notice">
            <?= $escaper->escapeHtml($viewModel->getNotificationText()) ?>
            <a target="_blank" href="<?= $escaper->escapeUrl($viewModel->getSuggestLink()) ?>">
                <?=  $escaper->escapeHtml(__('here')) ?>
            </a>.
        </p>
    </div>
<?php endif;?>
