<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Automatic Related Products for Magento 2
 */

use Amasty\Mostviewed\ViewModel\ProductSalesDemo;
use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/**
 * @var Template $block
 * @var Escaper $escaper
 * @var ProductSalesDemo $viewModel
 */

$viewModel = $block->getViewModel();
?>
<div class="message message-info">
    <div class="amrelated-product-sales-demo-message">
        <?= $escaper->escapeHtml('Enable the \'related-product-sales-report\' module to activate the Related Product Sales report. '
            . '(Note: This functionality is available as part of an active product subscription or support subscription. '
            . 'To upgrade and obtain this functionality, please follow the') ?>
        <a href="<?= $escaper->escapeUrl($viewModel->getSubscribeUrl() ?? '') ?>" target="_blank">
            <?= $escaper->escapeHtml('link') ?></a><?= $escaper->escapeHtml('.)') ?>
    </div>
</div>
<div class="product-sales-demo">
    <div class="product-sales-demo-link">
        <form action="<?= $escaper->escapeUrl($viewModel->getSubscribeUrl() ?? '') ?>" target="_blank">
            <button class=" action- scalable primary product-sales-demo-action">
                <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Amasty_Mostviewed::images/locked.svg')) ?>">
                <span><?= $escaper->escapeHtml(__('Unlock functionality')) ?></span>
            </button>
        </form>
    </div>
</div>
